using Microsoft.Extensions.Logging;

namespace Resume.Console
{
    public interface IProgramDescription
    {
        void Create();
    }

    public class ProgramDescription : IProgramDescription
    {
        private readonly ILogger<ProgramDescription> _logger;

        public ProgramDescription(ILogger<ProgramDescription> logger)
        {
            _logger = logger;
        }

        public void Create()
        {
            _logger.LogInformation(
                "Goal:\r\n" +
                "Get a job using a resume generated by a (slightly over-engineered) C# application which is part of the application for the job.\r\n" +
                "\r\n" +
                "Approach:\r\n" +
                "- Decide what type of application to build\r\n" +
                "- Create basic project structure using recommended/opinionated standards, found at:\r\n" +
                "-- https://gist.github.com/davidfowl/ed7564297c61fe9ab814 for the folder structure.\r\n" +
                "-- https://github.com/github/gitignore/blob/master/VisualStudio.gitignore for the git ignore file.\r\n" +
                "-- https://github.com/cwoodruff/ChinookASPNETCoreAPINTier for naming projects in a solution.\r\n" +
                "-- http://json.schemastore.org/resume for the JSON schema.\r\n" +
                "- Decide the TODO list:\r\n" +
                "-- Decide on how to load the resume data into a .NET solution.\r\n" +
                "-- Create the resume in JSON.\r\n" +
                "-- Read the JSON file.\r\n" +
                "-- Populate model properties using JSON (using the new .NET Core JSON API 'cause we can!)\r\n" +
                "-- Write to console after a step without referencing the Console project.\r\n" +
                "-- Decide on the PDF file generator to use.\r\n" +
                "-- Create a hello world PDF file with said file generator.\r\n" +
                "-- Combine the data with the PDF.\r\n" +
                "-- Fine-tuning/layout.\r\n" +
                "- Send in generated resume.\r\n" +
                "- Go apply for the job!\r\n");
        }
    }
}
